# Generated by Django 3.1.7 on 2023-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiements',
            name='address',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requiements',
            name='email',
            field=models.EmailField(default=456, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requiements',
            name='phone',
            field=models.IntegerField(default=789),
            preserve_default=False,
        ),
    ]
