# Generated by Django 3.1.7 on 2023-03-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0003_auto_20230320_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiements',
            name='material',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requiements',
            name='purpose',
            field=models.CharField(default=123, max_length=250),
            preserve_default=False,
        ),
    ]
