# Generated by Django 3.1.7 on 2023-03-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0004_auto_20230320_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='country',
            new_name='dept',
        ),
    ]
