# Generated by Django 3.1.7 on 2023-03-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0006_auto_20230321_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='age',
            field=models.CharField(max_length=15),
        ),
    ]
