# Generated by Django 3.1.7 on 2023-03-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0007_auto_20230321_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('name',), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
