# Generated by Django 3.1.7 on 2023-03-21 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeapp', '0008_auto_20230321_1959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
    ]
